# Generated by Django 3.0.5 on 2022-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='OtherCharge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='doctorFee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='medicineCost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='roomCharge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
