# Generated by Django 3.0.5 on 2022-03-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20220325_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='roomCharge',
            field=models.CharField(max_length=40),
        ),
    ]
