# Generated by Django 3.0.5 on 2022-03-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20220327_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pre_stat',
            field=models.BooleanField(default=False),
        ),
    ]
